### ISSUE TITLE
Исправить алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [dimangan/Uno-Soft_Test#1]
Дорбрый день, меня зовут Вадим, я разработчик компании UnoSoft.  
  
В проекте не представлен pom.xml, так что непонятно с какой java надо запускать проект, в jar архиве его так же нет.  
Я запустил на 17 java. На файле https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-4.txt.gz с ограничением по памяти в 1GB я получаю ошибку OutOfMemoryError. Поправьте её пожалуйста и добавьте pom.xml в проект.

**Comment by dimangan** [comment]
Доброй ночи! Все исправил, все добавил.
